/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioSourceRouteImport } from './routes/portfolio-source'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as IndexRouteImport } from './routes/index'

const PortfolioSourceRoute = PortfolioSourceRouteImport.update({
  id: '/portfolio-source',
  path: '/portfolio-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/portfolio-source': typeof PortfolioSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/portfolio-source': typeof PortfolioSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/portfolio-source': typeof PortfolioSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples' | '/portfolio-source'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples' | '/portfolio-source'
  id: '__root__' | '/' | '/examples' | '/portfolio-source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesRoute: typeof ExamplesRoute
  PortfolioSourceRoute: typeof PortfolioSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio-source': {
      id: '/portfolio-source'
      path: '/portfolio-source'
      fullPath: '/portfolio-source'
      preLoaderRoute: typeof PortfolioSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesRoute: ExamplesRoute,
  PortfolioSourceRoute: PortfolioSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
