/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as WeightRouteRouteImport } from './routes/weight/route'
import { Route as ClockRouteRouteImport } from './routes/clock/route'
import { Route as PortfolioRouteRouteImport } from './routes/_portfolio/route'
import { Route as WeightIndexRouteImport } from './routes/weight/index'
import { Route as ClockIndexRouteImport } from './routes/clock/index'
import { Route as PortfolioIndexRouteImport } from './routes/_portfolio/index'

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightRouteRoute = WeightRouteRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRouteRoute = ClockRouteRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRouteRoute = PortfolioRouteRouteImport.update({
  id: '/_portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightIndexRoute = WeightIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeightRouteRoute,
} as any)
const ClockIndexRoute = ClockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClockRouteRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortfolioIndexRoute
  '/clock': typeof ClockRouteRouteWithChildren
  '/weight': typeof WeightRouteRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/clock/': typeof ClockIndexRoute
  '/weight/': typeof WeightIndexRoute
}
export interface FileRoutesByTo {
  '/examples': typeof ExamplesRoute
  '/': typeof PortfolioIndexRoute
  '/clock': typeof ClockIndexRoute
  '/weight': typeof WeightIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portfolio': typeof PortfolioRouteRouteWithChildren
  '/clock': typeof ClockRouteRouteWithChildren
  '/weight': typeof WeightRouteRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/_portfolio/': typeof PortfolioIndexRoute
  '/clock/': typeof ClockIndexRoute
  '/weight/': typeof WeightIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clock' | '/weight' | '/examples' | '/clock/' | '/weight/'
  fileRoutesByTo: FileRoutesByTo
  to: '/examples' | '/' | '/clock' | '/weight'
  id:
    | '__root__'
    | '/_portfolio'
    | '/clock'
    | '/weight'
    | '/examples'
    | '/_portfolio/'
    | '/clock/'
    | '/weight/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortfolioRouteRoute: typeof PortfolioRouteRouteWithChildren
  ClockRouteRoute: typeof ClockRouteRouteWithChildren
  WeightRouteRoute: typeof WeightRouteRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portfolio': {
      id: '/_portfolio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortfolioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight/': {
      id: '/weight/'
      path: '/'
      fullPath: '/weight/'
      preLoaderRoute: typeof WeightIndexRouteImport
      parentRoute: typeof WeightRouteRoute
    }
    '/clock/': {
      id: '/clock/'
      path: '/'
      fullPath: '/clock/'
      preLoaderRoute: typeof ClockIndexRouteImport
      parentRoute: typeof ClockRouteRoute
    }
    '/_portfolio/': {
      id: '/_portfolio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRouteRoute
    }
  }
}

interface PortfolioRouteRouteChildren {
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteRouteChildren: PortfolioRouteRouteChildren = {
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteRouteWithChildren = PortfolioRouteRoute._addFileChildren(
  PortfolioRouteRouteChildren,
)

interface ClockRouteRouteChildren {
  ClockIndexRoute: typeof ClockIndexRoute
}

const ClockRouteRouteChildren: ClockRouteRouteChildren = {
  ClockIndexRoute: ClockIndexRoute,
}

const ClockRouteRouteWithChildren = ClockRouteRoute._addFileChildren(
  ClockRouteRouteChildren,
)

interface WeightRouteRouteChildren {
  WeightIndexRoute: typeof WeightIndexRoute
}

const WeightRouteRouteChildren: WeightRouteRouteChildren = {
  WeightIndexRoute: WeightIndexRoute,
}

const WeightRouteRouteWithChildren = WeightRouteRoute._addFileChildren(
  WeightRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PortfolioRouteRoute: PortfolioRouteRouteWithChildren,
  ClockRouteRoute: ClockRouteRouteWithChildren,
  WeightRouteRoute: WeightRouteRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
